export const TEMPLATES = [
  {
    id: 'hellokitty',
    name: 'Hello Kitty',
    emoji: '🎀',
    tagline: 'kawaii vibes ✨',
    bg: 'linear-gradient(135deg, #ffb7c5, #ff88aa, #ffcce0)',
    border: '#ff88aa',
    accent: '#ff4488',
    textColor: '#cc0066',
    decorations: ['🎀', '⭐', '🌸', '💕', '🎀', '⭐', '🍓', '💗'],
    particles: ['🎀', '🌸', '💕', '⭐', '🍓'],
    stripBg: 'linear-gradient(180deg, #ffb7c5 0%, #ffe4ee 50%, #ffb7c5 100%)',
    overlayText: 'HELLO KITTY',
    font: '"Playfair Display", serif',
    frameShape: 'rect',
  },
  {
    id: 'astronaut',
    name: 'Astronaut',
    emoji: '🚀',
    tagline: 'blast off 🌌',
    bg: 'linear-gradient(135deg, #0a0a2e, #1a1a4e, #0d1b3e)',
    border: '#4488ff',
    accent: '#00aaff',
    textColor: '#aaddff',
    decorations: ['🚀', '⭐', '🌙', '🌟', '🛸', '💫', '🌠', '🔭'],
    particles: ['🚀', '⭐', '🌙', '🛸', '💫'],
    stripBg: 'linear-gradient(180deg, #0a0a2e 0%, #1a2050 50%, #0a0a2e 100%)',
    overlayText: 'SPACE EXPLORER',
    font: '"Bebas Neue", cursive',
    frameShape: 'rect',
  },
  {
    id: 'lotso',
    name: 'Lotso',
    emoji: '🧸',
    tagline: 'huggy bear 🍓',
    bg: 'linear-gradient(135deg, #8B4513, #D2691E, #c77a3a)',
    border: '#D2691E',
    accent: '#ff6699',
    textColor: '#fff5e6',
    decorations: ['🧸', '🍓', '🌸', '💝', '🎠', '🌈', '🎡', '🎪'],
    particles: ['🧸', '🍓', '🌸', '💝', '🎠'],
    stripBg: 'linear-gradient(180deg, #8B4513 0%, #D2691E 50%, #8B4513 100%)',
    overlayText: 'LOTSO WORLD',
    font: '"Playfair Display", serif',
    frameShape: 'rect',
  },
  {
    id: 'starwars',
    name: 'Star Wars',
    emoji: '⚔️',
    tagline: 'may the force be with you',
    bg: 'linear-gradient(135deg, #000000, #1a0a00, #000000)',
    border: '#FFD700',
    accent: '#00ff88',
    textColor: '#FFD700',
    decorations: ['⚔️', '🌟', '🛸', '⭐', '🌌', '💫', '🔮', '⚡'],
    particles: ['⚔️', '⭐', '💫', '🌟', '🔮'],
    stripBg: 'linear-gradient(180deg, #000000 0%, #1a1a2e 50%, #000000 100%)',
    overlayText: 'A LONG TIME AGO...',
    font: '"Bebas Neue", cursive',
    frameShape: 'rect',
  },
  {
    id: 'dragonball',
    name: 'Dragon Ball',
    emoji: '🐉',
    tagline: 'power up! 🔥',
    bg: 'linear-gradient(135deg, #ff6f00, #e65100, #bf360c)',
    border: '#ffa000',
    accent: '#ffcc02',
    textColor: '#fff3e0',
    decorations: ['🐉', '⭐', '🔥', '💥', '⚡', '🌟', '✨', '🟠'],
    particles: ['🐉', '⭐', '🔥', '💥', '⚡'],
    stripBg: 'linear-gradient(180deg, #e65100 0%, #ff8f00 50%, #e65100 100%)',
    overlayText: 'KAMEHAMEHA!',
    font: '"Bebas Neue", cursive',
    frameShape: 'rect',
  },
  {
    id: 'onepiece',
    name: 'One Piece',
    emoji: '🏴‍☠️',
    tagline: 'set sail! ⚓',
    bg: 'linear-gradient(135deg, #01579b, #0277bd, #003c5f)',
    border: '#e53935',
    accent: '#29b6f6',
    textColor: '#e1f5fe',
    decorations: ['🏴‍☠️', '⚓', '🌊', '🗺️', '☠️', '⛵', '🧭', '💎'],
    particles: ['🏴‍☠️', '⚓', '🌊', '⛵', '💎'],
    stripBg: 'linear-gradient(180deg, #01579b 0%, #0288d1 50%, #01579b 100%)',
    overlayText: 'KING OF PIRATES',
    font: '"Bebas Neue", cursive',
    frameShape: 'rect',
  },
  {
    id: 'sakura',
    name: 'Sakura',
    emoji: '🌸',
    tagline: 'hanami season 🎐',
    bg: 'linear-gradient(135deg, #fce4ec, #f8bbd0, #f48fb1)',
    border: '#e91e63',
    accent: '#f06292',
    textColor: '#880e4f',
    decorations: ['🌸', '🎐', '🦋', '💮', '🌺', '🎀', '🌷', '✨'],
    particles: ['🌸', '🦋', '💮', '🌺', '✨'],
    stripBg: 'linear-gradient(180deg, #fce4ec 0%, #f8bbd0 50%, #fce4ec 100%)',
    overlayText: 'CHERRY BLOSSOM',
    font: '"Playfair Display", serif',
    frameShape: 'rect',
  },
  {
    id: 'omnom',
    name: 'Om Nom',
    emoji: '👾',
    tagline: 'Monster Green 👽',
    bg: 'linear-gradient(135deg, #1a0033, #2d004d, #0d0026)',
    border: '#00e676',
    accent: '#b388ff',
    textColor: '#e0e0e0',
    decorations: ['🎮', '👾', '🕹️', '⭐', '💎', '🏆', '🎯', '🔥'],
    particles: ['🎮', '👾', '🕹️', '⭐', '💎'],
    stripBg: 'linear-gradient(180deg, #1a0033 0%, #2d004d 50%, #1a0033 100%)',
    overlayText: 'MONSTER OM!',
    font: '"Bebas Neue", cursive',
    frameShape: 'rect',
  },

  // ============ NEW TEMPLATES ============

  {
    id: 'lovepink',
    name: 'Love Pink 💗',
    emoji: '💗',
    tagline: 'spread love 💕',
    bg: 'linear-gradient(135deg, #ff4d6d, #ff85a1, #ffc2d1)',
    border: '#ff4d6d',
    accent: '#ff85a1',
    textColor: '#fff0f3',
    decorations: ['💗', '💕', '💝', '💖', '🌹', '✨', '💫', '🎀'],
    particles: ['💗', '💕', '💝', '🌹', '✨'],
    stripBg: 'linear-gradient(180deg, #ff4d6d 0%, #ff85a1 50%, #ff4d6d 100%)',
    overlayText: 'WITH LOVE',
    font: '"Playfair Display", serif',
    frameShape: 'heart',
  },
  {
    id: 'bubblegum',
    name: 'Bubblegum 🫧',
    emoji: '🫧',
    tagline: 'pop & fun! 🍬',
    bg: 'linear-gradient(135deg, #f9f0ff, #e8d5fb, #d4b6f5)',
    border: '#b24aec',
    accent: '#f472b6',
    textColor: '#6b21a8',
    decorations: ['🍬', '🍭', '🫧', '⭐', '🌈', '✨', '🍡', '🎠'],
    particles: ['🍬', '🍭', '🫧', '🌈', '✨'],
    stripBg: 'linear-gradient(180deg, #f3e8ff 0%, #e9d5ff 50%, #f3e8ff 100%)',
    overlayText: 'BUBBLEGUM BLISS',
    font: '"Playfair Display", serif',
    frameShape: 'circle',
  },
  {
    id: 'vintagefilm',
    name: 'Vintage Film 🎞️',
    emoji: '🎞️',
    tagline: 'old is gold 📸',
    bg: 'linear-gradient(135deg, #3d2b1f, #7b4f35, #c49a6c)',
    border: '#c49a6c',
    accent: '#e8c99a',
    textColor: '#f5edd6',
    decorations: ['📸', '🎞️', '⌛', '🗝️', '📺', '🎬', '📷', '🌿'],
    particles: ['📸', '🎞️', '⌛', '📷', '🌿'],
    stripBg: 'linear-gradient(180deg, #5c3d28 0%, #8b5e3c 50%, #5c3d28 100%)',
    overlayText: 'VINTAGE MEMORIES',
    font: '"Playfair Display", serif',
    frameShape: 'polaroid',
  },
  {
    id: 'neonnight',
    name: 'Neon Night 🌃',
    emoji: '🌃',
    tagline: 'glow in the dark ⚡',
    bg: 'linear-gradient(135deg, #020024, #090979, #00d4ff)',
    border: '#00d4ff',
    accent: '#ff00ff',
    textColor: '#e0ffff',
    decorations: ['⚡', '🌃', '💎', '🔮', '✨', '🌙', '⭐', '🎆'],
    particles: ['⚡', '💎', '🔮', '✨', '🌙'],
    stripBg: 'linear-gradient(180deg, #020024 0%, #09097a 50%, #020024 100%)',
    overlayText: 'NEON DREAMS',
    font: '"Bebas Neue", cursive',
    frameShape: 'hexagon',
  },
  {
    id: 'y2k',
    name: 'Y2K Vibes 💿',
    emoji: '💿',
    tagline: 'back to the 2000s 🦋',
    bg: 'linear-gradient(135deg, #c8f0fa, #b0d9f5, #f5d0e8)',
    border: '#7ab8f5',
    accent: '#f5a0c8',
    textColor: '#003366',
    decorations: ['💿', '🦋', '⭐', '🌀', '📱', '💾', '🎵', '✨'],
    particles: ['💿', '🦋', '⭐', '🌀', '🎵'],
    stripBg: 'linear-gradient(180deg, #d4f1f9 0%, #e8f4fd 50%, #d4f1f9 100%)',
    overlayText: 'Y2K FOREVER',
    font: '"Bebas Neue", cursive',
    frameShape: 'diamond',
  },
  {
    id: 'cottagecore',
    name: 'Cottagecore 🌼',
    emoji: '🌼',
    tagline: 'simple & sweet 🍄',
    bg: 'linear-gradient(135deg, #f0e6d3, #e8d5b7, #dbc09a)',
    border: '#a07850',
    accent: '#8cb87a',
    textColor: '#4a3728',
    decorations: ['🌼', '🍄', '🌿', '🦋', '🌾', '🌻', '🍃', '🌸'],
    particles: ['🌼', '🍄', '🌿', '🦋', '🌾'],
    stripBg: 'linear-gradient(180deg, #f2e8d5 0%, #e5d0b0 50%, #f2e8d5 100%)',
    overlayText: 'COTTAGE DREAMS',
    font: '"Playfair Display", serif',
    frameShape: 'arch',
  },
  {
    id: 'kiddie',
    name: 'Kiddie Fun 🎈',
    emoji: '🎈',
    tagline: 'fun for everyone! 🎉',
    bg: 'linear-gradient(135deg, #ffeb3b, #ff9800, #e91e63)',
    border: '#ff5722',
    accent: '#4caf50',
    textColor: '#fff8e1',
    decorations: ['🎈', '🎉', '🎊', '⭐', '🦄', '🌈', '🎀', '🍭'],
    particles: ['🎈', '🎉', '🦄', '🌈', '🍭'],
    stripBg: 'linear-gradient(180deg, #fff176 0%, #ffe082 50%, #fff176 100%)',
    overlayText: 'FUN TIMES!',
    font: '"Bebas Neue", cursive',
    frameShape: 'cloud',
  },
  {
    id: 'galaxygirl',
    name: 'Galaxy Girl 🌌',
    emoji: '🌌',
    tagline: 'shine like a star 🌟',
    bg: 'linear-gradient(135deg, #1a0540, #3b0764, #7c3aed)',
    border: '#a855f7',
    accent: '#ec4899',
    textColor: '#fdf4ff',
    decorations: ['🌌', '⭐', '💜', '🌟', '🔮', '✨', '🌙', '💫'],
    particles: ['🌌', '⭐', '💜', '🔮', '✨'],
    stripBg: 'linear-gradient(180deg, #1a0540 0%, #3b0764 50%, #1a0540 100%)',
    overlayText: 'GALAXY QUEEN',
    font: '"Bebas Neue", cursive',
    frameShape: 'star',
  },
  {
    id: 'summer',
    name: 'Summer Vibes ☀️',
    emoji: '☀️',
    tagline: 'sunny & fun 🌊',
    bg: 'linear-gradient(135deg, #ff9a3c, #ff6b35, #ffd23f)',
    border: '#ff6b35',
    accent: '#00bcd4',
    textColor: '#fff8e1',
    decorations: ['☀️', '🌊', '🏄', '🌺', '🍹', '🌴', '🐚', '🦀'],
    particles: ['☀️', '🌊', '🏄', '🌺', '🍹'],
    stripBg: 'linear-gradient(180deg, #ff9a3c 0%, #ffb347 50%, #ff9a3c 100%)',
    overlayText: 'SUMMER MEMORIES',
    font: '"Bebas Neue", cursive',
    frameShape: 'wave',
  },
  {
    id: 'aesthetic',
    name: 'Aesthetic 🤍',
    emoji: '🤍',
    tagline: 'minimal & clean ✨',
    bg: 'linear-gradient(135deg, #f8f9fa, #e9ecef, #dee2e6)',
    border: '#6c757d',
    accent: '#adb5bd',
    textColor: '#212529',
    decorations: ['🤍', '🪷', '🌿', '☁️', '✨', '🕊️', '🌙', '⭐'],
    particles: ['🤍', '🪷', '🌿', '☁️', '✨'],
    stripBg: 'linear-gradient(180deg, #ffffff 0%, #f5f5f5 50%, #ffffff 100%)',
    overlayText: 'AESTHETICALLY YOURS',
    font: '"Playfair Display", serif',
    frameShape: 'oval',
  },
  {
    id: 'matcha',
    name: 'Matcha 🍵',
    emoji: '🍵',
    tagline: 'green & serene 🌿',
    bg: 'linear-gradient(135deg, #1a4a2e, #2d7a4a, #4caf7e)',
    border: '#4caf7e',
    accent: '#a5d6a7',
    textColor: '#f1f8e9',
    decorations: ['🍵', '🌿', '🍃', '🎋', '🌾', '✨', '🪴', '🌸'],
    particles: ['🍵', '🌿', '🍃', '🎋', '🌾'],
    stripBg: 'linear-gradient(180deg, #1a4a2e 0%, #2d7a4a 50%, #1a4a2e 100%)',
    overlayText: 'MATCHA MOMENTS',
    font: '"Playfair Display", serif',
    frameShape: 'rect',
  },
]

export function getTemplate(id) {
  return TEMPLATES.find(t => t.id === id) || TEMPLATES[0]
}
