export const TEMPLATES = [
  {
    id: 'hellokitty',
    name: 'Hello Kitty',
    emoji: '🎀',
    tagline: 'kawaii vibes ✨',
    bg: 'linear-gradient(135deg, #ffb7c5, #ff88aa, #ffcce0)',
    border: '#ff88aa',
    accent: '#ff4488',
    textColor: '#cc0066',
    decorations: ['🎀', '⭐', '🌸', '💕', '🎀', '⭐', '🍓', '💗'],
    particles: ['🎀', '🌸', '💕', '⭐', '🍓'],
    stripBg: 'linear-gradient(180deg, #ffb7c5 0%, #ffe4ee 50%, #ffb7c5 100%)',
    overlayText: 'HELLO KITTY',
    font: '"Playfair Display", serif',
  },
  {
    id: 'astronaut',
    name: 'Astronaut',
    emoji: '🚀',
    tagline: 'blast off 🌌',
    bg: 'linear-gradient(135deg, #0a0a2e, #1a1a4e, #0d1b3e)',
    border: '#4488ff',
    accent: '#00aaff',
    textColor: '#aaddff',
    decorations: ['🚀', '⭐', '🌙', '🌟', '🛸', '💫', '🌠', '🔭'],
    particles: ['🚀', '⭐', '🌙', '🛸', '💫'],
    stripBg: 'linear-gradient(180deg, #0a0a2e 0%, #1a2050 50%, #0a0a2e 100%)',
    overlayText: 'SPACE EXPLORER',
    font: '"Bebas Neue", cursive',
  },
  {
    id: 'lotso',
    name: 'Lotso',
    emoji: '🧸',
    tagline: 'huggy bear 🍓',
    bg: 'linear-gradient(135deg, #8B4513, #D2691E, #c77a3a)',
    border: '#D2691E',
    accent: '#ff6699',
    textColor: '#fff5e6',
    decorations: ['🧸', '🍓', '🌸', '💝', '🎠', '🌈', '🎡', '🎪'],
    particles: ['🧸', '🍓', '🌸', '💝', '🎠'],
    stripBg: 'linear-gradient(180deg, #8B4513 0%, #D2691E 50%, #8B4513 100%)',
    overlayText: 'LOTSO WORLD',
    font: '"Playfair Display", serif',
  },
  {
    id: 'starwars',
    name: 'Star Wars',
    emoji: '⚔️',
    tagline: 'may the force be with you',
    bg: 'linear-gradient(135deg, #000000, #1a0a00, #000000)',
    border: '#FFD700',
    accent: '#00ff88',
    textColor: '#FFD700',
    decorations: ['⚔️', '🌟', '🛸', '⭐', '🌌', '💫', '🔮', '⚡'],
    particles: ['⚔️', '⭐', '💫', '🌟', '🔮'],
    stripBg: 'linear-gradient(180deg, #000000 0%, #1a1a2e 50%, #000000 100%)',
    overlayText: 'A LONG TIME AGO...',
    font: '"Bebas Neue", cursive',
  },
]

export function getTemplate(id) {
  return TEMPLATES.find(t => t.id === id) || TEMPLATES[0]
}
