export const TEMPLATES = [
  {
    id: 'hellokitty',
    name: 'Hello Kitty',
    emoji: '🎀',
    tagline: 'kawaii vibes ✨',
    bg: 'linear-gradient(135deg, #ffb7c5, #ff88aa, #ffcce0)',
    border: '#ff88aa',
    accent: '#ff4488',
    textColor: '#cc0066',
    decorations: ['🎀', '⭐', '🌸', '💕', '🎀', '⭐', '🍓', '💗'],
    particles: ['🎀', '🌸', '💕', '⭐', '🍓'],
    stripBg: 'linear-gradient(180deg, #ffb7c5 0%, #ffe4ee 50%, #ffb7c5 100%)',
    overlayText: 'HELLO KITTY',
    font: '"Playfair Display", serif',
  },
  {
    id: 'astronaut',
    name: 'Astronaut',
    emoji: '🚀',
    tagline: 'blast off 🌌',
    bg: 'linear-gradient(135deg, #0a0a2e, #1a1a4e, #0d1b3e)',
    border: '#4488ff',
    accent: '#00aaff',
    textColor: '#aaddff',
    decorations: ['🚀', '⭐', '🌙', '🌟', '🛸', '💫', '🌠', '🔭'],
    particles: ['🚀', '⭐', '🌙', '🛸', '💫'],
    stripBg: 'linear-gradient(180deg, #0a0a2e 0%, #1a2050 50%, #0a0a2e 100%)',
    overlayText: 'SPACE EXPLORER',
    font: '"Bebas Neue", cursive',
  },
  {
    id: 'lotso',
    name: 'Lotso',
    emoji: '🧸',
    tagline: 'huggy bear 🍓',
    bg: 'linear-gradient(135deg, #8B4513, #D2691E, #c77a3a)',
    border: '#D2691E',
    accent: '#ff6699',
    textColor: '#fff5e6',
    decorations: ['🧸', '🍓', '🌸', '💝', '🎠', '🌈', '🎡', '🎪'],
    particles: ['🧸', '🍓', '🌸', '💝', '🎠'],
    stripBg: 'linear-gradient(180deg, #8B4513 0%, #D2691E 50%, #8B4513 100%)',
    overlayText: 'LOTSO WORLD',
    font: '"Playfair Display", serif',
  },
  {
    id: 'starwars',
    name: 'Star Wars',
    emoji: '⚔️',
    tagline: 'may the force be with you',
    bg: 'linear-gradient(135deg, #000000, #1a0a00, #000000)',
    border: '#FFD700',
    accent: '#00ff88',
    textColor: '#FFD700',
    decorations: ['⚔️', '🌟', '🛸', '⭐', '🌌', '💫', '🔮', '⚡'],
    particles: ['⚔️', '⭐', '💫', '🌟', '🔮'],
    stripBg: 'linear-gradient(180deg, #000000 0%, #1a1a2e 50%, #000000 100%)',
    overlayText: 'A LONG TIME AGO...',
    font: '"Bebas Neue", cursive',
  },
  {
    id: 'dragonball',
    name: 'Dragon Ball',
    emoji: '🐉',
    tagline: 'power up! 🔥',
    bg: 'linear-gradient(135deg, #ff6f00, #e65100, #bf360c)',
    border: '#ffa000',
    accent: '#ffcc02',
    textColor: '#fff3e0',
    decorations: ['🐉', '⭐', '🔥', '💥', '⚡', '🌟', '✨', '🟠'],
    particles: ['🐉', '⭐', '🔥', '💥', '⚡'],
    stripBg: 'linear-gradient(180deg, #e65100 0%, #ff8f00 50%, #e65100 100%)',
    overlayText: 'KAMEHAMEHA!',
    font: '"Bebas Neue", cursive',
  },
  {
    id: 'onepiece',
    name: 'One Piece',
    emoji: '🏴‍☠️',
    tagline: 'set sail! ⚓',
    bg: 'linear-gradient(135deg, #01579b, #0277bd, #003c5f)',
    border: '#e53935',
    accent: '#29b6f6',
    textColor: '#e1f5fe',
    decorations: ['🏴‍☠️', '⚓', '🌊', '🗺️', '☠️', '⛵', '🧭', '💎'],
    particles: ['🏴‍☠️', '⚓', '🌊', '⛵', '💎'],
    stripBg: 'linear-gradient(180deg, #01579b 0%, #0288d1 50%, #01579b 100%)',
    overlayText: 'KING OF PIRATES',
    font: '"Bebas Neue", cursive',
  },
  {
    id: 'sakura',
    name: 'Sakura',
    emoji: '🌸',
    tagline: 'hanami season 🎐',
    bg: 'linear-gradient(135deg, #fce4ec, #f8bbd0, #f48fb1)',
    border: '#e91e63',
    accent: '#f06292',
    textColor: '#880e4f',
    decorations: ['🌸', '🎐', '🦋', '💮', '🌺', '🎀', '🌷', '✨'],
    particles: ['🌸', '🦋', '💮', '🌺', '✨'],
    stripBg: 'linear-gradient(180deg, #fce4ec 0%, #f8bbd0 50%, #fce4ec 100%)',
    overlayText: 'CHERRY BLOSSOM',
    font: '"Playfair Display", serif',
  },
  {
    id: 'omnom',
    name: 'Om Nom',
    emoji: '👾',
    tagline: 'Monster Green 👽',
    bg: 'linear-gradient(135deg, #1a0033, #2d004d, #0d0026)',
    border: '#00e676',
    accent: '#b388ff',
    textColor: '#e0e0e0',
    decorations: ['🎮', '👾', '🕹️', '⭐', '💎', '🏆', '🎯', '🔥'],
    particles: ['🎮', '👾', '🕹️', '⭐', '💎'],
    stripBg: 'linear-gradient(180deg, #1a0033 0%, #2d004d 50%, #1a0033 100%)',
    overlayText: 'MONSTER OM!',
    font: '"Bebas Neue", cursive',
  },
]

export function getTemplate(id) {
  return TEMPLATES.find(t => t.id === id) || TEMPLATES[0]
}
